// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHumeVxCqp_wBrx0pwWn3CNvY_D57HCgQ',
    appId: '1:687104636907:web:067bf2e8c862c4bf850bae',
    messagingSenderId: '687104636907',
    projectId: 'bookt-fba34',
    authDomain: 'bookt-fba34.firebaseapp.com',
    storageBucket: 'bookt-fba34.firebasestorage.app',
    measurementId: 'G-KM9DE11QGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJFUwDHy52_PlTX0ym6SDtF5hQOiyDIvk',
    appId: '1:687104636907:android:bfe593a4daa2cdee850bae',
    messagingSenderId: '687104636907',
    projectId: 'bookt-fba34',
    storageBucket: 'bookt-fba34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_DhRoeJrBxhwhALUEekCQcRZWFJtWmW0',
    appId: '1:687104636907:ios:264d79b85cd2003a850bae',
    messagingSenderId: '687104636907',
    projectId: 'bookt-fba34',
    storageBucket: 'bookt-fba34.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
}
